apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec: 
        containers:
          - name: {{ .Release.Name }}
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            ports:
              - containerPort: 8000
            env:
              - name: MODEL_PATH
                value: {{ .Values.env.MODEL_PATH }}